version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: collaborative_app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collaborative_app
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pfa_net

  traefik:
    image: traefik:v2.10
    container_name: collabro_traefik
    restart: always
    environment:
      - DOCKER_API_VERSION=1.41
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=pfa_net"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - pfa_net

networks:
  pfa_net:
    name: pfa_net
    external: true

volumes:
  mysql_data:
